version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: ssh myza@${duntek_host} "cd /var/www/duntek.ru && git clone git@github.com:Sepuka/myzaapp.git"
      - run: ssh myza@${duntek_host} "cd /var/www/duntek.ru && composer install"

workflows:
  sample:
    jobs:
      - build