version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: scp -r -o "StrictHostKeyChecking no" * myza@${duntek_host}:/var/www/duntek.ru
      - run: ssh myza@${duntek_host} "chown -R :www-data /var/www/duntek.ru/log"
      - run: ssh myza@${duntek_host} "chmod g+w /var/www/duntek.ru/log/log.txt"

workflows:
  sample:
    jobs:
      - build