version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: ssh -o StrictHostKeyChecking=no myza@${duntek_host} "cd /var/www/duntek.ru && git pull"
      - run: ssh myza@${duntek_host} "cd /var/www/duntek.ru && php ./init --env=Production --overwrite=All --delete=All"
      - run: ssh myza@${duntek_host} "cd /var/www/duntek.ru && composer install"

workflows:
  sample:
    jobs:
      - build